### PR TITLE
Ftr: add nacos registry

### PR DESCRIPTION
**Pull request by onewe**
relate #46

### CODE REVIEW

**Comment by yang20150702** [comment]
Good Work. I suggest that you can add example about nacos registry in examples.

**Comment by onewe** [comment]
OK, I will add an example soon

**Comment by onewe** [comment]
By now, the dubbo server side can not add customizable registry. It need a mechanism which can dynamic load plugin , but it's so hard.

Doesn't use rust ffi implement it?

**Comment by robberphex** [comment]
Don't change extension mechanism at this PR, we could change extension mechanism in another PR.

**Comment by onewe** [comment]
Ok, I won't do that.

**Comment by yang20150702** [comment]
LGTM

**Pull request merged**
