### PR TITLE
Fix: 修复服务无法注册异常

### PR DESCRIPTION
**Pull request by hubertshelley**

### CODE REVIEW

**Review by AlbumenJ — COMMENTED** [review]
@robberphex @yang20150702 PTAL

**Comment by yang20150702** [comment]
ok, please fix failed error. @hubertshelley

**Comment by yang20150702** [comment]
please fix failed ci. @hubertshelley

**Comment by yang20150702** [comment]
Good work. Please fix failed ci. @hubertshelley

**Comment by yang20150702** [comment]
LGTM, thanks for your work

**Pull request merged**
